[package]
name = "audio-metadata"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
publish = false

[lints.clippy]
missing_const_for_thread_local = "allow"

[dependencies]
bytes = "1.5.0"
encoding_rs = "0.8.35"
lofty = "0.24.0"
thiserror = { workspace = true }
storage-backend = { path = "../storage-backend" }
async-runtime = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
